  cards= [
    {"duration": "30", "text": "get desssed"},
    {"duration": "30", "text": "brush teeth"},
    {"duration": "30", "text": "harvest"},
    {"duration": "10", "text": "drain grains"},
    {"duration": "15", "text": "clear sink"},
    {"duration": "15", "text": "gather supplies"},
    {"duration": "10", "text": "prep PC's"},
    {"duration": "10", "text": "open spawn bags"},
    {"duration": "0", "text": "set up jars"},
    {"duration": "0", "text": "fill PC water"},
    {"duration": "10", "text": "break up grains"},
    {"duration": "10", "text": "cut liners"},
    {"duration": "10", "text": "fill bags"},
    {"duration": "0", "text": "fill jars"},
    {"duration": "10", "text": "fold bags"},
    {"duration": "5", "text": "lids/foil on jars"},
    {"duration": "15", "text": "load PC's"},
    {"duration": "5", "text": "start PC's"},
    {"duration": "15", "text": "clean up"},
    {"duration": "20", "text": "break"},
    {"duration": "10", "text": "soak grains"},
    {"duration": "5", "text": "set up tubs"},
    {"duration": "5", "text": "wipe tubs down"},
    {"duration": "5", "text": "remove old tape"},
    {"duration": "5", "text": "tape holes"},
    {"duration": "5", "text": "label tubs/ buckets"},
    {"duration": "5", "text": "drain grains 1"},
    {"duration": "15", "text": "line tubs"},
    {"duration": "5", "text": "wipe liners down"},
    {"duration": "5", "text": "distribute grains 1"},
    {"duration": "5", "text": "drain grains 2"},
    {"duration": "15", "text": "hydrate substrate 1"},
    {"duration": "5", "text": "distribute substrate 1"},
    {"duration": "15", "text": "hydrate substrate 2"},
    {"duration": "5", "text": "distribute grains 2"},
    {"duration": "5", "text": "distribute substrate 2"},
    {"duration": "15", "text": "mix tubs"},
    {"duration": "15", "text": "trim liners"},
    {"duration": "15", "text": "level tubs"},
    {"duration": "10", "text": "put tubs away"},
    {"duration": "30", "text": "clean up"}
  ]

module.exports = cards;
